// Seed position data for local development mock DB
// Large object mapping moment IDs to position arrays

import { STD } from './devSeedData.js'

export const SEED_POSITIONS = {
  // ── Page 5: Rey León — posició inicial ────────────────────────
  'dev-m-01-1': [
    { member_id: 'dev-m-s2-lm',  grid_row: 1, grid_col: 2 },
    { member_id: 'dev-m-s1-cd',  grid_row: 1, grid_col: 3 },
    { member_id: 'dev-m-a2-mg',  grid_row: 1, grid_col: 4 },
    { member_id: 'dev-m-a2-ar',  grid_row: 1, grid_col: 5 },
    { member_id: 'dev-m-a1-sr',  grid_row: 1, grid_col: 6 },
    { member_id: 'dev-m-t1-aa',  grid_row: 1, grid_col: 7 },
    { member_id: 'dev-m-bas-4',  grid_row: 1, grid_col: 8 },
    { member_id: 'dev-m-bar-5',  grid_row: 1, grid_col: 9 },
    { member_id: 'dev-m-s1-mf',  grid_row: 2, grid_col: 1 },
    { member_id: 'dev-m-a1-mk',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-a2-mfm', grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-a1-mt',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-t1-jm',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-t1-mp',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-s2-ms',  grid_row: 3, grid_col: 1 },
    { member_id: 'dev-m-s2-gl',  grid_row: 3, grid_col: 2 },
    { member_id: 'dev-m-s1-sk',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-a2-cg',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-a1-ap',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-a1-ng',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-t1-ll',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-js',  grid_row: 4, grid_col: 2 },
    { member_id: 'dev-m-s2-ic',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-a2-am',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-t1-sp',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-t1-dr',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-bas-1',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-bar-2',  grid_row: 4, grid_col: 10 },
  ],
  // ── Page 6: Rey León — "night and a voice" ────────────────────
  // (7 members floating above T4 are skipped; AiP/PV at Terra edges)
  'dev-m-01-2': [
    { member_id: 'dev-m-a2-mfm', grid_row: 1, grid_col: 4 },
    { member_id: 'dev-m-a1-mt',  grid_row: 1, grid_col: 5 },
    { member_id: 'dev-m-t1-ss',  grid_row: 1, grid_col: 6 },
    { member_id: 'dev-m-t1-jm',  grid_row: 1, grid_col: 7 },
    { member_id: 'dev-m-t1-mp',  grid_row: 1, grid_col: 8 },
    { member_id: 'dev-m-bas-2',  grid_row: 1, grid_col: 9 },
    { member_id: 'dev-m-bar-3',  grid_row: 1, grid_col: 10 },
    { member_id: 'dev-m-s2-lm',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-s1-mf',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-a1-mk',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bar-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bar-4',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-s2-ms',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-s2-gl',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-s1-sk',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-a1-ng',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-t1-ll',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-s2-js',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-a2-cg',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-ai',  grid_row: 5, grid_col: 1 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-bas-3',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a1-sc',  grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-t1-sp',  grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-bar-2',  grid_row: 5, grid_col: 13 },
  ],
  // ── Page 7: Rey León — "They live in you" ─────────────────────
  'dev-m-01-3': [
    { member_id: 'dev-m-s2-lm',  grid_row: 1, grid_col: 2 },
    { member_id: 'dev-m-s1-cd',  grid_row: 1, grid_col: 3 },
    { member_id: 'dev-m-a2-mg',  grid_row: 1, grid_col: 4 },
    { member_id: 'dev-m-a2-ar',  grid_row: 1, grid_col: 5 },
    { member_id: 'dev-m-a1-sr',  grid_row: 1, grid_col: 6 },
    { member_id: 'dev-m-t1-aa',  grid_row: 1, grid_col: 7 },
    { member_id: 'dev-m-bas-4',  grid_row: 1, grid_col: 8 },
    { member_id: 'dev-m-bar-5',  grid_row: 1, grid_col: 9 },
    { member_id: 'dev-m-s1-mf',  grid_row: 2, grid_col: 1 },
    { member_id: 'dev-m-a1-mk',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-a2-mfm', grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-a1-mt',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-t1-jm',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-t1-mp',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-s2-ms',  grid_row: 3, grid_col: 1 },
    { member_id: 'dev-m-s2-gl',  grid_row: 3, grid_col: 2 },
    { member_id: 'dev-m-s1-sk',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-a1-sc',  grid_row: 3, grid_col: 4 },  // SC↔CG swapped vs p5
    { member_id: 'dev-m-a1-ap',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-a1-ng',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-t1-ll',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-js',  grid_row: 4, grid_col: 2 },
    { member_id: 'dev-m-s2-ic',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-a2-am',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-a2-cg',  grid_row: 4, grid_col: 5 },  // CG here instead of SC
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-t1-sp',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-t1-dr',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-bas-1',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-bar-2',  grid_row: 4, grid_col: 10 },
  ],
  // ── Page 8: The Seal Lullaby ───────────────────────────────────
  'dev-m-02-1': [
    { member_id: 'dev-m-s2-ic',  grid_row: 1, grid_col: 2 },
    { member_id: 'dev-m-s2-lm',  grid_row: 1, grid_col: 3 },
    { member_id: 'dev-m-a2-mg',  grid_row: 1, grid_col: 4 },
    { member_id: 'dev-m-a1-mt',  grid_row: 1, grid_col: 5 },
    { member_id: 'dev-m-a1-sc',  grid_row: 1, grid_col: 6 },
    { member_id: 'dev-m-t1-aa',  grid_row: 1, grid_col: 7 },
    { member_id: 'dev-m-t1-jm',  grid_row: 1, grid_col: 8 },
    { member_id: 'dev-m-bas-2',  grid_row: 1, grid_col: 9 },
    { member_id: 'dev-m-bas-1',  grid_row: 1, grid_col: 10 },
    { member_id: 'dev-m-s1-cd',  grid_row: 2, grid_col: 1 },
    { member_id: 'dev-m-s1-mf',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-a1-mk',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-a2-cg',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-a1-ng',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-t1-sp',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-4',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-bar-1',  grid_row: 2, grid_col: 10 },
    { member_id: 'dev-m-s2-js',  grid_row: 3, grid_col: 1 },
    { member_id: 'dev-m-s2-gl',  grid_row: 3, grid_col: 2 },
    { member_id: 'dev-m-a2-am',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-a1-sr',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-a1-ap',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-t1-ll',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-t1-dr',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 2 },
    { member_id: 'dev-m-s1-sk',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-a2-mfm', grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-a2-ar',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-t1-mp',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-bar-3',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-bar-5',  grid_row: 4, grid_col: 9 },
  ],
  // ── Page 9: Euphoria — intro ───────────────────────────────────
  'dev-m-03-1': [
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-t1-ll',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-t1-mp',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-t1-aa',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-t1-jm',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-5',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-s2-gl',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-s1-cd',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-mk',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-mt',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 10 },
    { member_id: 'dev-m-a1-sr',  grid_row: 4, grid_col: 11 },
    { member_id: 'dev-m-a2-cg',  grid_row: 5, grid_col: 1 },
    { member_id: 'dev-m-a2-ar',  grid_row: 5, grid_col: 2 },
    { member_id: 'dev-m-a1-ng',  grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-s1-mf',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-s2-lm',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a2-mfm', grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 8 },
    { member_id: 'dev-m-s1-sk',  grid_row: 5, grid_col: 9 },
    { member_id: 'dev-m-a2-mg',  grid_row: 5, grid_col: 10 },
    { member_id: 'dev-m-s2-js',  grid_row: 5, grid_col: 11 },
    { member_id: 'dev-m-t1-sp',  grid_row: 5, grid_col: 12 },
  ],
  // ── Page 10: Euphoria — primera tornada ───────────────────────
  'dev-m-03-2': [
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-t1-ll',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-t1-mp',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-t1-aa',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-t1-jm',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-t1-sp',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-5',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-s2-gl',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-s1-cd',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-mk',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-mt',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 10 },
    { member_id: 'dev-m-a1-sr',  grid_row: 4, grid_col: 11 },
    { member_id: 'dev-m-a2-cg',  grid_row: 5, grid_col: 1 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 2 },
    { member_id: 'dev-m-a2-mfm', grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-a2-mg',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-a1-ng',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a2-ar',  grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-s2-js',  grid_row: 5, grid_col: 8 },
    { member_id: 'dev-m-s2-lm',  grid_row: 5, grid_col: 9 },
    { member_id: 'dev-m-s1-sk',  grid_row: 5, grid_col: 10 },
    { member_id: 'dev-m-s1-mf',  grid_row: 5, grid_col: 11 },
  ],
  // ── Page 11: Euphoria — "we are free we..." ───────────────────
  'dev-m-03-3': [
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-t1-ll',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-t1-mp',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-t1-aa',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-t1-jm',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-t1-sp',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-5',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-s2-gl',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-s1-cd',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-mk',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-mt',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 10 },
    { member_id: 'dev-m-a1-sr',  grid_row: 4, grid_col: 11 },
    { member_id: 'dev-m-a2-cg',  grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-a2-ar',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a2-mfm', grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-a2-mg',  grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-s2-lm',  grid_row: 5, grid_col: 9 },
    { member_id: 'dev-m-s1-sk',  grid_row: 5, grid_col: 10 },
    { member_id: 'dev-m-s1-mf',  grid_row: 5, grid_col: 11 },
    { member_id: 'dev-m-s2-js',  grid_row: 5, grid_col: 12 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 13 },
    { member_id: 'dev-m-a1-ng',  grid_row: 5, grid_col: 8 },
  ],
  // ── Page 12: Euphoria — "we're higher" + 2a tornada ──────────
  'dev-m-03-4': [
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-t1-ll',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-t1-mp',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-t1-aa',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-t1-jm',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-t1-sp',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-5',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-s2-gl',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-s1-cd',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-mk',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-mt',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 10 },
    { member_id: 'dev-m-a1-sr',  grid_row: 4, grid_col: 11 },
    { member_id: 'dev-m-a2-cg',  grid_row: 5, grid_col: 2 },
    { member_id: 'dev-m-a2-mfm', grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-a2-mg',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-a2-ar',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-dir',    grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-s1-sk',  grid_row: 5, grid_col: 9 },
    { member_id: 'dev-m-s2-js',  grid_row: 5, grid_col: 10 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 11 },
    { member_id: 'dev-m-s1-mf',  grid_row: 5, grid_col: 12 },
    { member_id: 'dev-m-s2-lm',  grid_row: 5, grid_col: 13 },
  ],
  // ── Page 13/14: Euphoria — última tornada ─────────────────────
  'dev-m-03-5': [
    { member_id: 'dev-m-t1-ss',  grid_row: 2, grid_col: 2 },
    { member_id: 'dev-m-t1-dr',  grid_row: 2, grid_col: 3 },
    { member_id: 'dev-m-t1-ll',  grid_row: 2, grid_col: 4 },
    { member_id: 'dev-m-bas-4',  grid_row: 2, grid_col: 5 },
    { member_id: 'dev-m-bas-2',  grid_row: 2, grid_col: 6 },
    { member_id: 'dev-m-bas-1',  grid_row: 2, grid_col: 7 },
    { member_id: 'dev-m-bas-3',  grid_row: 2, grid_col: 8 },
    { member_id: 'dev-m-bar-2',  grid_row: 2, grid_col: 9 },
    { member_id: 'dev-m-t1-mp',  grid_row: 3, grid_col: 3 },
    { member_id: 'dev-m-t1-aa',  grid_row: 3, grid_col: 4 },
    { member_id: 'dev-m-t1-jm',  grid_row: 3, grid_col: 5 },
    { member_id: 'dev-m-t1-sp',  grid_row: 3, grid_col: 6 },
    { member_id: 'dev-m-bar-4',  grid_row: 3, grid_col: 7 },
    { member_id: 'dev-m-bar-1',  grid_row: 3, grid_col: 8 },
    { member_id: 'dev-m-bar-3',  grid_row: 3, grid_col: 9 },
    { member_id: 'dev-m-bar-5',  grid_row: 3, grid_col: 10 },
    { member_id: 'dev-m-s2-ms',  grid_row: 4, grid_col: 3 },
    { member_id: 'dev-m-s2-gl',  grid_row: 4, grid_col: 4 },
    { member_id: 'dev-m-s1-cd',  grid_row: 4, grid_col: 5 },
    { member_id: 'dev-m-a1-mk',  grid_row: 4, grid_col: 6 },
    { member_id: 'dev-m-a1-ap',  grid_row: 4, grid_col: 7 },
    { member_id: 'dev-m-a1-mt',  grid_row: 4, grid_col: 8 },
    { member_id: 'dev-m-a1-sc',  grid_row: 4, grid_col: 9 },
    { member_id: 'dev-m-a1-ai',  grid_row: 4, grid_col: 10 },
    { member_id: 'dev-m-a1-sr',  grid_row: 4, grid_col: 11 },
    { member_id: 'dev-m-a1-ng',  grid_row: 4, grid_col: 12 },
    { member_id: 'dev-m-a2-cg',  grid_row: 5, grid_col: 2 },
    { member_id: 'dev-m-a2-mfm', grid_row: 5, grid_col: 3 },
    { member_id: 'dev-m-a2-ar',  grid_row: 5, grid_col: 4 },
    { member_id: 'dev-m-a2-mg',  grid_row: 5, grid_col: 5 },
    { member_id: 'dev-m-a2-am',  grid_row: 5, grid_col: 6 },
    { member_id: 'dev-m-dir',    grid_row: 5, grid_col: 7 },
    { member_id: 'dev-m-s1-sk',  grid_row: 5, grid_col: 9 },
    { member_id: 'dev-m-s2-js',  grid_row: 5, grid_col: 10 },
    { member_id: 'dev-m-s2-ic',  grid_row: 5, grid_col: 11 },
    { member_id: 'dev-m-s1-mf',  grid_row: 5, grid_col: 12 },
    { member_id: 'dev-m-s2-lm',  grid_row: 5, grid_col: 13 },
  ],
  // ── Standard pyramid (remaining songs, approximated from PDF style) ──
  'dev-m-04-1': STD, 'dev-m-05-1': STD, 'dev-m-06-1': STD,
  'dev-m-07-1': STD, 'dev-m-07-2': STD, 'dev-m-07-3': STD, 'dev-m-07-4': STD,
  'dev-m-08-1': STD, 'dev-m-08-2': STD, 'dev-m-08-3': STD, 'dev-m-08-4': STD, 'dev-m-08-5': STD,
  'dev-m-09-1': STD, 'dev-m-09-2': STD, 'dev-m-09-3': STD, 'dev-m-09-4': STD,
  'dev-m-10-1': STD,
  'dev-m-11-1': STD,
  'dev-m-12-1': STD, 'dev-m-12-2': STD, 'dev-m-12-3': STD,
  'dev-m-13-1': STD, 'dev-m-13-2': STD, 'dev-m-13-3': STD, 'dev-m-13-4': STD,
  'dev-m-14-1': STD, 'dev-m-14-2': STD, 'dev-m-14-3': STD,
  'dev-m-15-1': STD, 'dev-m-15-2': STD,
  'dev-m-16-01': STD, 'dev-m-16-02': STD, 'dev-m-16-03': STD, 'dev-m-16-04': STD, 'dev-m-16-05': STD,
  'dev-m-16-06': STD, 'dev-m-16-07': STD, 'dev-m-16-08': STD, 'dev-m-16-09': STD, 'dev-m-16-10': STD,
  'dev-m-16-11': STD, 'dev-m-16-12': STD, 'dev-m-16-13': STD, 'dev-m-16-14': STD, 'dev-m-16-15': STD,
}
